### ISSUE TITLE
[PE-D][Tester C] Bug when calling `addtask` command, displaying wrong error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-1/tp#145]
When using addtask and input to parameter t/ is empty, error message displayed is for name instead of tag

![image.png](https://raw.githubusercontent.com/KevinEyo1/ped/main/files/d44f417f-591a-4d96-88dc-eec0882fde0d.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: KevinEyo1/ped#3

**Comment by toh-xinyi** [comment]
- New exception to change error message
